[WIP] Add squash and archive history functionality
bdionne/protege-client pull request #14
Opened 2017-05-06 00:58 UTC by AnthonyMl

TODO:
- remove ontolgy ids from history and snapshot files

2017-05-08 17:19 UTC, rgrinberg approved these changes
LGTM. Seems simple enough

2017-05-08 21:34 UTC, bdionne commented
this looks good. As commented on revision-history:#4 I'd like to wait and merge all three repos at the same time, as part of a new build

2017-05-30 16:34 UTC, rgrinberg requested changes

2017-05-30 16:34 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +	private ProgressDialog dlg = new ProgressDialog();
Can we scope these instance variables to the methods where they're being used?

The ProgressDialog initialization fails for some unit tests for example.

2017-06-02 16:17 UTC, bdionne commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +			response = get(SERVER_STATUS);
This constant is not defined

2017-06-02 17:05 UTC, AnthonyMl commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +			response = get(SERVER_STATUS);
Its in
src/main/java/org/protege/editor/owl/server/http/ServerEndpoints.java
in the protege-server pr

2017-06-02 17:22 UTC, bdionne commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +			response = get(SERVER_STATUS);
oh ok, I probably haven't pulled latest from there

2017-06-05 23:48 UTC, rgrinberg approved these changes

2017-06-06 14:05 UTC, rgrinberg commented
@AnthonyMl Add some `@Nonnull` annotations on the projectId's methods that you've just added/modified.

2017-06-06 19:39 UTC, bdionne commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +	private SnapShot retrieveDocumentSnapshotFromServerResponse(Response response, @Nonnull ProjectId projectId)
this seems odd, it's declared nonnull then there's a check for a null, and either way the variable is never used?

2017-06-06 19:45 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +	private SnapShot retrieveDocumentSnapshotFromServerResponse(Response response, @Nonnull ProjectId projectId)
The boilerplate is there for 2 reasons:

1) Nonnull allows intellij to try and look for places in the code where a null parameter might be passed in.
2) The null check will give a decent error message if it actually occurs at runtime. (These checks can be removed once we're confident that we really aren't passing nulls)

And we are actually using the projectId. It's just that we were erroneously getting it from the instance variable where it was null.

2017-06-06 19:49 UTC, bdionne commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +	private SnapShot retrieveDocumentSnapshotFromServerResponse(Response response, @Nonnull ProjectId projectId)
? - I think it was an instance variable by design, passing them in is a change

2017-06-06 21:25 UTC, rgrinberg commented
The last commit gets rid of that `projectId` local variable entirely. One place where I'd like to see review are those `isWorkflowManager` and `isWorflowModeler` calls. Right now when those client calls fail I'm simply converting them to exceptions. Where the old behavior was to return false. Seems like this is slightly safer. But would like some confirmation there.

2017-06-06 22:40 UTC, bdionne commented
-0 on this last commit.

2017-06-06 23:15 UTC, rgrinberg commented
I addressed the objections to the last commit. The semantics for modeler/manager checking should now be identical. It still seems worrisome to me that we can swallow any client exception in those calls but at least it's safe for now.

Note that this change also requires tweaking nci-edit-tab as well. So I will make that change as well.

2017-06-07 01:21 UTC, AnthonyMl commented on src/main/java/org/protege/editor/owl/client/LocalHttpClient.java
> +			get(GEN_CON_HIST + "?projectid=" + projectId);
We need the ```.get()``` here.
toString is different than just the internal id.

2017-06-08 21:39 UTC, rgrinberg commented
closed in favor of #20

2017-06-08 21:49 UTC, closed without merging